
/*
 * This file describes standard stats and strategies of
 * the base (unmodded) game.
 *
 * If you want to make an AI specially designed for your mod, start by
 * making a copy of this file and modifying it according to your mod's rules.
 *
 * Then provide a personality to use the ruleset, similar to
 * how nb_generic.[js|ai] is provided for this ruleset.
 *
 * You may find some useful functions for working with these stats
 * in stats.js .
 *
 */

// a factor for figuring out how large things are in this ruleset,
// or simply a typical radius of a player's base
const baseScale = 40;

// diameter of laser satellite splash/incendiary damage
// for use in lassat.js
const lassatSplash = 4;

// set this to 1 to choose templates randomly, instead of later=>better.
const randomTemplates = 1;

// this function is used for avoiding AI cheats that appear due to
// being able to build droids before designing them
function iCanDesign() {
	if (difficulty === INSANE) // won't make INSANE much worse ...
		return true;
	return countFinishedStructList(structures.hqs) > 0;
}

const structures = {
	factories: [ "A0LightFactory", "WreckedTransporter" ,"OldFactory", "A0CyborgFactory"],
	templateFactories: [ "A0CyborgFactory", ],
	vtolFactories: [ "A0VTolFactory1", ],
	labs: [ "A0ResearchFacility", "Laseropticslab", ],
	gens: [ "A0PowerGenerator", "A0BaBaPowerGenerator",],
	hqs: [ "A0CommandCentre", ],
	vtolPads: [ "A0VtolPad", ],
	derricks: [ "A0ResourceExtractor" ,],
	extras: [ "A0RepairCentre3", "A0Sat-linkCentre", "A0LasSatCommand" ],
//	powerstuff: ["AirTrafficControl-nrs", "Propaganda-nrs","WaterTower-nrs","OilTower-nrs", "Park-nrs","Forest-nrs","Tree-nrs","BigForest-nrs","NuclearReactor","SolarPower-nrs","Powlab-nrs","Advmaterialslab-nrs","Aerodynamicslab-nrs","Ruin1-nrs","BarbHUT-nrs","cabin-nrs","building10-nrs","LogCabin3-nrs","building12-nrs","building11-nrs","building2-nrs","building3-nrs","BarbWarehouse1-nrs","BarbWarehouse2-nrs","BarbWarehouse3-nrs","Rotarywepslab-nrs","Heavywepslab-nrs" ],
	powerstuff: ["OilTower-eco","BarbWarehouse2-eco","Forest-eco","Heavywepslab-eco","LogCabin3-eco","BigForest-eco","cabin-eco","Powlab-eco","Park-eco","building11-eco","AirTrafficControl-eco","Pickup-eco","building10-eco","Ruin1-eco","Aerodynamicslab-eco","Boulder3-eco","Tree-eco","building12-eco","CoolingTower-eco","SolarPower-eco","Rotarywepslab-eco","Boulder1-eco","Boulder2-eco","building3-eco","Advmaterialslab-eco","A0ResourceExtractor-eco"],
	//powerstuff: ["A0RepairCentre3","AirTrafficControl-nrs","OilTower-nrs","WaterTower-nrs","Propaganda-nrs","Aerodynamicslab-nrs","Advmaterialslab-nrs","Powlab-nrs","SolarPower-nrs","NuclearReactor","BigForest-nrs","Tree-nrs","Forest-nrs","Park-nrs","road-nrs","Heavywepslab-nrs","Rotarywepslab-nrs","BarbWarehouse3-nrs","BarbWarehouse2-nrs","BarbWarehouse1-nrs","building3-nrs","building2-nrs","building11-nrs","building12-nrs","LogCabin3-nrs","building10-nrs","cabin-nrs","BarbHUT-nrs","Ruin1-nrs","A0FacMod1","A0PowMod1"],
	sensors: [ "Sys-SensoTower02", "Sys-CB-Tower01", "Sys-RadarDetector01", "Sys-SensoTowerWS", ],
};

const oilResources = [ "OilResource", ];

const powerUps = [ "OilDrum", "Crate" ];

// NOTE: you cannot use specific stats as bases, but only stattypes
// probably better make use of .name rather than of .stattype here?
const modules = [
	{ base: POWER_GEN, module: "A0PowMod1", count: 1, cost: MODULECOST.CHEAP },
	{ base: FACTORY, module: "A0FacMod1", count: 2, cost: MODULECOST.EXPENSIVE },
	{ base: VTOL_FACTORY, module: "A0FacMod1", count: 2, cost: MODULECOST.EXPENSIVE },
	{ base: RESEARCH_LAB, module: "A0ResearchModule1", count: 1, cost: MODULECOST.EXPENSIVE },
];

const targets = []
	.concat(structures.derricks)
	.concat(structures.derricks)
	.concat(structures.derricks)
	.concat(structures.factories)
	.concat(structures.factories)
	.concat(structures.templateFactories)
	.concat(structures.templateFactories)
	.concat(structures.vtolFactories)
	.concat(structures.extras)
	.concat(structures.powerstuff)
;

const miscTargets = []
	.concat(structures.derricks)
	.concat(structures.powerstuff)
;

const sensorTurrets = [
	"SensorTurret1Mk1", // sensor
	"Sensor-WideSpec", // wide spectrum sensor
];
//BarbHUT,building10,building3,Park,AirTrafficControl
//"BigForest-eco","LogCabin3-eco","Heavywepslab-eco","Forest-eco","cabin-eco","OilTower-eco"]
const fundamentalResearch = [
	//"R-NRS-road-nrs",
	"R-NRS-A0BaBaFactory",
	"R-NRS-tracked01",
	//"R-NRS-CyborgHeavyBody-2120",
	"R-NRS-A0RepairCentre3",
	//"R-NRS-A0CyborgFactory",
	//"R-NRS-NuclearReactor",
	//"R-NRS-Park-nrs",
	"R-NRS-BigForest-eco3",
	"R--ResearchPoints--3",
	"R--ProductionPoints--3",
	"R-NRS-LogCabin3-eco3",
	"R--ResearchPoints--6",
	"R--ProductionPoints--6",
	"R--ResearchPoints--9",
	"R--ProductionPoints--9",	
	"R-Sys-Autorepair-General",
	"R-NRS-Heavywepslab-eco3",
	//"R-hover01-HitpointPctOfBody-9",
	//"R-wheeled01-HitpointPctOfBody-9",
	"R-NRS-Forest-eco3",
	"R--Range--9",
	"R-NRS-OilTower-eco3",
	/*
	"R-Struc-RprFac-Upgrade01",
	"R-Sys-Sensor-Tower02",
	"R-Vehicle-Prop-Halftracks",
	"R-Struc-Power-Upgrade01c",
	"R-Vehicle-Prop-Tracks",
	"R-Sys-CBSensor-Tower01",
	"R-Struc-VTOLPad-Upgrade01",
	"R-Struc-Power-Upgrade03a",
	"R-Struc-VTOLPad-Upgrade03",
	"R-Sys-Autorepair-General",
	"R-Wpn-LasSat",
	"R-Struc-RprFac-Upgrade04",
	"R-Struc-VTOLPad-Upgrade06",
	"R-Struc-RprFac-Upgrade06",
	*/
];

const fastestResearch = [
	"R--ResearchPoints--9",
];

// body and propulsion arrays don't affect fixed template droids
const bodyStats = [
			{ res: "R-NRS-B2crane1", stat: "B2crane1", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B2crane2", stat: "B2crane2", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ScavNEXUSbody", stat: "ScavNEXUSbody", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-HeavyChopper", stat: "HeavyChopper", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body11ABT", stat: "Body11ABT", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body6SUPP", stat: "Body6SUPP", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body7SUPP-2120", stat: "Body7SUPP-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body16MED-contingency", stat: "Body16MED-contingency", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body21MED-contingency", stat: "Body21MED-contingency", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-ScavengerChopper", stat: "ScavengerChopper", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body5REC", stat: "Body5REC", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ZNULLBODY", stat: "ZNULLBODY", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body21SUP-2120", stat: "Body21SUP-2120", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body15LGT-contingency", stat: "Body15LGT-contingency", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body10MBT", stat: "Body10MBT", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body9REC", stat: "Body9REC", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ChinookBody-2120", stat: "ChinookBody-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-ScavNEXUStrack", stat: "ScavNEXUStrack", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body8UPG-2120", stat: "Body8UPG-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body12SUP", stat: "Body12SUP", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body7ABT", stat: "Body7ABT", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body3ALT-2120", stat: "Body3ALT-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body1UPG-2120", stat: "Body1UPG-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body4UPG-2120", stat: "Body4UPG-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body17SUP-2120", stat: "Body17SUP-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body19REC-2120", stat: "Body19REC-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body20ABT-2120", stat: "Body20ABT-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body22SUPP-2120", stat: "Body22SUPP-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body23REC-2120", stat: "Body23REC-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body19HVY-contingency", stat: "Body19HVY-contingency", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body1REC", stat: "Body1REC", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body2SUP", stat: "Body2SUP", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body3MBT", stat: "Body3MBT", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body4ABT", stat: "Body4ABT", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body8MBT", stat: "Body8MBT", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body3SUP-2120", stat: "Body3SUP-2120", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body18MED-contingency", stat: "Body18MED-contingency", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-B2tractor", stat: "B2tractor", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ScavIcevanBody", stat: "ScavIcevanBody", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ScavTruckBody", stat: "ScavTruckBody", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B2JeepBody-Ultimate", stat: "B2JeepBody-Ultimate", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B2RKJeepBody-Ultimate", stat: "B2RKJeepBody-Ultimate", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ScavCamperBody", stat: "ScavCamperBody", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B3body-sml-buggy01-Ultimate", stat: "B3body-sml-buggy01-Ultimate", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B3bodyRKbuggy01-Ultimate", stat: "B3bodyRKbuggy01", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B4body-sml-trike01-Ultimate", stat: "B4body-sml-trike01-Ultimate", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body15ABT-2120", stat: "Body15ABT-2120", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body18REC-2120", stat: "Body18REC-2120", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-ScavengerChopper2-contingency", stat: "ScavengerChopper2-contingency", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body17LGT-contingency", stat: "Body17LGT-contingency", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body20LGT-contingency", stat: "Body20LGT-contingency", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body16MBT-2120", stat: "Body16MBT-2120", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Superbody-2120", stat: "Superbody-2120", weight: WEIGHT.LIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-B2JeepBody", stat: "B2JeepBody", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B2RKJeepBody", stat: "B2RKJeepBody", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B3body-sml-buggy01", stat: "B3body-sml-buggy01", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B3bodyRKbuggy01", stat: "B3bodyRKbuggy01", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-BusBody", stat: "BusBody", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-FireBody", stat: "FireBody", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-B4body-sml-trike01", stat: "B4body-sml-trike01", weight: WEIGHT.ULTRALIGHT , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body13SUP", stat: "Body13SUP", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body14SUP", stat: "Body14SUP", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body17SUUP-2120", stat: "Body17SUUP-2120", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body25DKD-2120", stat: "Body25DKD-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body10REC-2120", stat: "Body10REC-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body23SUP-contingency", stat: "Body23SUP-contingency", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body25SUP-contingency", stat: "Body25SUP-contingency", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-TransporterBody", stat: "TransporterBody", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body15ABTT-2120", stat: "Body15ABTT-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body16MBTT-2120", stat: "Body16MBTT-2120", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body24DKL-2120", stat: "Body24DKL-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body22HVY-contingency", stat: "Body22HVY-contingency", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body13ABT-2120", stat: "Body13ABT-2120", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body10ALT-2120", stat: "Body10ALT-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body7ALT-2120", stat: "Body7ALT-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body11UPG-2120", stat: "Body11UPG-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body12UPG-2120", stat: "Body12UPG-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-Body12SUPP-2120", stat: "Body12SUPP-2120", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body26SUP-2120", stat: "Body26SUP-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body27SUP-2120", stat: "Body27SUP-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body28SUP-2120", stat: "Body28SUP-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.THERMAL },
			{ res: "R-NRS-Body24SUP-contingency", stat: "Body24SUP-contingency", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-SuperTransportBody", stat: "SuperTransportBody", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-GunshipBody-2120", stat: "GunshipBody-2120", weight: WEIGHT.ULTRAHEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-CyborgLightBody", stat: "CyborgLightBody", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-CyborgHeavyBody", stat: "CyborgHeavyBody", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-CyborgHeavyBody-2120", stat: "CyborgHeavyBody-2120", weight: WEIGHT.HEAVY , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-A0BaBaFactory", stat: "B1BaBaPerson01-nrs", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-A0BaBaFactory", stat: "", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
			{ res: "R-NRS-A0BaBaFactory", stat: "", weight: WEIGHT.MEDIUM , usage: BODYUSAGE.UNIVERSAL, armor: BODYCLASS.KINETIC },
	
];

const classResearch = {
	kinetic: [
		[ // OBJTYPE.TANK
			//"R-Droids-HitPointPct--9",
						"R-NRS-B2crane1",
			"R-NRS-B2crane2",
			"R-NRS-ScavNEXUSbody",
			"R-NRS-HeavyChopper",
			"R-NRS-Body11ABT",
			"R-NRS-Body6SUPP",
			"R-NRS-Body7SUPP-2120",
			"R-NRS-ScavengerChopper",
			"R-NRS-Body5REC",
			"R-NRS-ZNULLBODY",
			"R-NRS-Body21SUP-2120",
			"R-NRS-Body10MBT",
			"R-NRS-Body9REC",
			"R-NRS-ScavNEXUStrack",
			"R-NRS-Body8UPG-2120",
			"R-NRS-Body7ABT",
			"R-NRS-Body1UPG-2120",
			"R-NRS-Body4UPG-2120",
			"R-NRS-Body19REC-2120",
			"R-NRS-Body20ABT-2120",
			"R-NRS-Body22SUPP-2120",
			"R-NRS-Body23REC-2120",
			"R-NRS-Body1REC",
			"R-NRS-Body2SUP",
			"R-NRS-Body3MBT",
			"R-NRS-Body3SUP-2120",
			"R-NRS-B2tractor",
			"R-NRS-ScavIcevanBody",
			"R-NRS-ScavTruckBody",
			"R-NRS-B2JeepBody-Ultimate",
			"R-NRS-B2RKJeepBody-Ultimate",
			"R-NRS-ScavCamperBody",
			"R-NRS-B3body-sml-buggy01-Ultimate",
			"R-NRS-B3bodyRKbuggy01-Ultimate",
			"R-NRS-B4body-sml-trike01-Ultimate",
			"R-NRS-Body18REC-2120",
			"R-NRS-B2JeepBody",
			"R-NRS-B2RKJeepBody",
			"R-NRS-B3body-sml-buggy01",
			"R-NRS-B3bodyRKbuggy01",
			"R-NRS-BusBody",
			"R-NRS-FireBody",
			"R-NRS-B4body-sml-trike01",
			"R-NRS-Body17SUUP-2120",
			"R-NRS-Body25DKD-2120",
			"R-NRS-Body23SUP-contingency",
			"R-NRS-Body25SUP-contingency",
			"R-NRS-TransporterBody",
			"R-NRS-Body15ABTT-2120",
			"R-NRS-Body16MBTT-2120",
			"R-NRS-Body24DKL-2120",
			"R-NRS-Body11UPG-2120",
			"R-NRS-Body12UPG-2120",
			"R-NRS-Body24SUP-contingency",
			"R-NRS-SuperTransportBody",
			"R-NRS-GunshipBody-2120",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",

			"R-tracked01-HitpointPctOfBody--9",
		],
		[ // OBJTYPE.BORG
			//"R-Droids-HitPointPct--9",
						"R-NRS-B2crane1",
			"R-NRS-B2crane2",
			"R-NRS-ScavNEXUSbody",
			"R-NRS-HeavyChopper",
			"R-NRS-Body11ABT",
			"R-NRS-Body6SUPP",
			"R-NRS-Body7SUPP-2120",
			"R-NRS-ScavengerChopper",
			"R-NRS-Body5REC",
			"R-NRS-ZNULLBODY",
			"R-NRS-Body21SUP-2120",
			"R-NRS-Body10MBT",
			"R-NRS-Body9REC",
			"R-NRS-ScavNEXUStrack",
			"R-NRS-Body8UPG-2120",
			"R-NRS-Body7ABT",
			"R-NRS-Body1UPG-2120",
			"R-NRS-Body4UPG-2120",
			"R-NRS-Body19REC-2120",
			"R-NRS-Body20ABT-2120",
			"R-NRS-Body22SUPP-2120",
			"R-NRS-Body23REC-2120",
			"R-NRS-Body1REC",
			"R-NRS-Body2SUP",
			"R-NRS-Body3MBT",
			"R-NRS-Body3SUP-2120",
			"R-NRS-B2tractor",
			"R-NRS-ScavIcevanBody",
			"R-NRS-ScavTruckBody",
			"R-NRS-B2JeepBody-Ultimate",
			"R-NRS-B2RKJeepBody-Ultimate",
			"R-NRS-ScavCamperBody",
			"R-NRS-B3body-sml-buggy01-Ultimate",
			"R-NRS-B3bodyRKbuggy01-Ultimate",
			"R-NRS-B4body-sml-trike01-Ultimate",
			"R-NRS-Body18REC-2120",
			"R-NRS-B2JeepBody",
			"R-NRS-B2RKJeepBody",
			"R-NRS-B3body-sml-buggy01",
			"R-NRS-B3bodyRKbuggy01",
			"R-NRS-BusBody",
			"R-NRS-FireBody",
			"R-NRS-B4body-sml-trike01",
			"R-NRS-Body17SUUP-2120",
			"R-NRS-Body25DKD-2120",
			"R-NRS-Body23SUP-contingency",
			"R-NRS-Body25SUP-contingency",
			"R-NRS-TransporterBody",
			"R-NRS-Body15ABTT-2120",
			"R-NRS-Body16MBTT-2120",
			"R-NRS-Body24DKL-2120",
			"R-NRS-Body11UPG-2120",
			"R-NRS-Body12UPG-2120",
			"R-NRS-Body24SUP-contingency",
			"R-NRS-SuperTransportBody",
			"R-NRS-GunshipBody-2120",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",

			"R-CyborgLegs-HitpointPctOfBody--18",
		],
		[ // OBJTYPE.DEFS			
			"R-Wall-HitPoints--18",
						"R-NRS-B2crane1",
			"R-NRS-B2crane2",
			"R-NRS-ScavNEXUSbody",
			"R-NRS-HeavyChopper",
			"R-NRS-Body11ABT",
			"R-NRS-Body6SUPP",
			"R-NRS-Body7SUPP-2120",
			"R-NRS-ScavengerChopper",
			"R-NRS-Body5REC",
			"R-NRS-ZNULLBODY",
			"R-NRS-Body21SUP-2120",
			"R-NRS-Body10MBT",
			"R-NRS-Body9REC",
			"R-NRS-ScavNEXUStrack",
			"R-NRS-Body8UPG-2120",
			"R-NRS-Body7ABT",
			"R-NRS-Body1UPG-2120",
			"R-NRS-Body4UPG-2120",
			"R-NRS-Body19REC-2120",
			"R-NRS-Body20ABT-2120",
			"R-NRS-Body22SUPP-2120",
			"R-NRS-Body23REC-2120",
			"R-NRS-Body1REC",
			"R-NRS-Body2SUP",
			"R-NRS-Body3MBT",
			"R-NRS-Body3SUP-2120",
			"R-NRS-B2tractor",
			"R-NRS-ScavIcevanBody",
			"R-NRS-ScavTruckBody",
			"R-NRS-B2JeepBody-Ultimate",
			"R-NRS-B2RKJeepBody-Ultimate",
			"R-NRS-ScavCamperBody",
			"R-NRS-B3body-sml-buggy01-Ultimate",
			"R-NRS-B3bodyRKbuggy01-Ultimate",
			"R-NRS-B4body-sml-trike01-Ultimate",
			"R-NRS-Body18REC-2120",
			"R-NRS-B2JeepBody",
			"R-NRS-B2RKJeepBody",
			"R-NRS-B3body-sml-buggy01",
			"R-NRS-B3bodyRKbuggy01",
			"R-NRS-BusBody",
			"R-NRS-FireBody",
			"R-NRS-B4body-sml-trike01",
			"R-NRS-Body17SUUP-2120",
			"R-NRS-Body25DKD-2120",
			"R-NRS-Body23SUP-contingency",
			"R-NRS-Body25SUP-contingency",
			"R-NRS-TransporterBody",
			"R-NRS-Body15ABTT-2120",
			"R-NRS-Body16MBTT-2120",
			"R-NRS-Body24DKL-2120",
			"R-NRS-Body11UPG-2120",
			"R-NRS-Body12UPG-2120",
			"R-NRS-Body24SUP-contingency",
			"R-NRS-SuperTransportBody",
			"R-NRS-GunshipBody-2120",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",
			"R-NRS-A0BaBaFactory",

		],
		[ // OBJTYPE.VTOL
			//"R-Droids-HitPointPct--9",
		],
	],
	thermal: [
		[ // OBJTYPE.TANK
						"R-NRS-Body16MED-contingency",
			"R-NRS-Body21MED-contingency",
			"R-NRS-Body15LGT-contingency",
			"R-NRS-ChinookBody-2120",
			"R-NRS-Body12SUP",
			"R-NRS-Body3ALT-2120",
			"R-NRS-Body17SUP-2120",
			"R-NRS-Body19HVY-contingency",
			"R-NRS-Body4ABT",
			"R-NRS-Body8MBT",
			"R-NRS-Body18MED-contingency",
			"R-NRS-Body15ABT-2120",
			"R-NRS-ScavengerChopper2-contingency",
			"R-NRS-Body17LGT-contingency",
			"R-NRS-Body20LGT-contingency",
			"R-NRS-Body16MBT-2120",
			"R-NRS-Superbody-2120",
			"R-NRS-Body13SUP",
			"R-NRS-Body14SUP",
			"R-NRS-Body10REC-2120",
			"R-NRS-Body22HVY-contingency",
			"R-NRS-Body13ABT-2120",
			"R-NRS-Body10ALT-2120",
			"R-NRS-Body7ALT-2120",
			"R-NRS-Body12SUPP-2120",
			"R-NRS-Body26SUP-2120",
			"R-NRS-Body27SUP-2120",
			"R-NRS-Body28SUP-2120",

			"R-tracked01-HitpointPctOfBody--9",
			//"R-Droids-HitPointPct--9",
		],
		[ // OBJTYPE.BORG
						"R-NRS-Body16MED-contingency",
			"R-NRS-Body21MED-contingency",
			"R-NRS-Body15LGT-contingency",
			"R-NRS-ChinookBody-2120",
			"R-NRS-Body12SUP",
			"R-NRS-Body3ALT-2120",
			"R-NRS-Body17SUP-2120",
			"R-NRS-Body19HVY-contingency",
			"R-NRS-Body4ABT",
			"R-NRS-Body8MBT",
			"R-NRS-Body18MED-contingency",
			"R-NRS-Body15ABT-2120",
			"R-NRS-ScavengerChopper2-contingency",
			"R-NRS-Body17LGT-contingency",
			"R-NRS-Body20LGT-contingency",
			"R-NRS-Body16MBT-2120",
			"R-NRS-Superbody-2120",
			"R-NRS-Body13SUP",
			"R-NRS-Body14SUP",
			"R-NRS-Body10REC-2120",
			"R-NRS-Body22HVY-contingency",
			"R-NRS-Body13ABT-2120",
			"R-NRS-Body10ALT-2120",
			"R-NRS-Body7ALT-2120",
			"R-NRS-Body12SUPP-2120",
			"R-NRS-Body26SUP-2120",
			"R-NRS-Body27SUP-2120",
			"R-NRS-Body28SUP-2120",

			"R-CyborgLegs-HitpointPctOfBody--18",
			//"R-Droids-HitPointPct--9",
		],
		[ // OBJTYPE.DEFS
			"R-Wall-HitPoints--18",
						"R-NRS-Body16MED-contingency",
			"R-NRS-Body21MED-contingency",
			"R-NRS-Body15LGT-contingency",
			"R-NRS-ChinookBody-2120",
			"R-NRS-Body12SUP",
			"R-NRS-Body3ALT-2120",
			"R-NRS-Body17SUP-2120",
			"R-NRS-Body19HVY-contingency",
			"R-NRS-Body4ABT",
			"R-NRS-Body8MBT",
			"R-NRS-Body18MED-contingency",
			"R-NRS-Body15ABT-2120",
			"R-NRS-ScavengerChopper2-contingency",
			"R-NRS-Body17LGT-contingency",
			"R-NRS-Body20LGT-contingency",
			"R-NRS-Body16MBT-2120",
			"R-NRS-Superbody-2120",
			"R-NRS-Body13SUP",
			"R-NRS-Body14SUP",
			"R-NRS-Body10REC-2120",
			"R-NRS-Body22HVY-contingency",
			"R-NRS-Body13ABT-2120",
			"R-NRS-Body10ALT-2120",
			"R-NRS-Body7ALT-2120",
			"R-NRS-Body12SUPP-2120",
			"R-NRS-Body26SUP-2120",
			"R-NRS-Body27SUP-2120",
			"R-NRS-Body28SUP-2120",

		],
		[ // OBJTYPE.VTOL
			//"R-Droids-HitPointPct--9",
		],
	],
};

// NOTE: Please don't put hover propulsion into the ground list, etc.!
// NOTE: Hover propulsion should be placed AFTER ground propulsion!
// Adaptation code relies on that for discovering map topology.
// Ground propulsions need to be ground only, hover propulsions shouldn't
// be able to cross cliffs, but should be able to cross seas, etc.
const propulsionStats = [
	{ res: "R-NRS-wheeled01", stat: "wheeled01", usage: PROPULSIONUSAGE.GROUND },
	{ res: "R-NRS-HalfTrack", stat: "HalfTrack", usage: PROPULSIONUSAGE.GROUND },
	{ res: "R-NRS-tracked01", stat: "tracked01", usage: PROPULSIONUSAGE.GROUND },
	{ res: "R-NRS-hover01", stat: "hover01", usage: PROPULSIONUSAGE.HOVER },
	//{ res: "R-Vehicle-Prop-VTOL", stat: "V-Tol", usage: PROPULSIONUSAGE.VTOL },
];


const truckTurrets = [
	"Spade1Mk1",
];

const truckTemplates = [
	{ body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "CyborgSpade", ] } // engineer
];

const fallbackWeapon = 'APO₽N';

// Unlike bodies and propulsions, weapon lines don't have any specific meaning.
// You can make as many weapon lines as you want for your ruleset.
const weaponStats = {
	APE21 : {
		roles : [ 0.1, 0.5, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 6,
		weapons : [
			{ res: "R-NRS-Laser-AP1-contingency", stat: "Laser-AP1-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-Laser-AP2-contingency", stat: "Laser-AP2-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Laser-AP3-contingency", stat: "Laser-AP3-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-Laser-AP4-contingency", stat: "Laser-AP4-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser-AA2-contingency", stat: "Laser-AA2-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser-Sonic-contingency", stat: "Laser-Sonic-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Laser-AP1-contingency", stat: "walltower-Laser-AP1-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AP2-contingency", stat: "walltower-Laser-AP2-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AP3-contingency", stat: "walltower-Laser-AP3-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AP4-contingency", stat: "walltower-Laser-AP4-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AA2-contingency", stat: "walltower-Laser-AA2-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-Sonic-contingency", stat: "walltower-Laser-Sonic-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Laser-AP1-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AP1-contingency", ] },
			{ res: "R-NRS-Laser-AP2-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AP2-contingency", ] },
			{ res: "R-NRS-Laser-AP3-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AP3-contingency", ] },
			{ res: "R-NRS-Laser-AP4-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AP4-contingency", ] },
			{ res: "R-NRS-Laser-AA2-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AA2-contingency", ] },
			{ res: "R-NRS-Laser-Sonic-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-Sonic-contingency", ] },
		],
		extras: [
		],
	},
	ATE11 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 103,
		weapons : [
			{ res: "R-NRS-Laser-AT1-contingency", stat: "Laser-AT1-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-Laser-AT2-contingency", stat: "Laser-AT2-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Laser-AT3-contingency", stat: "Laser-AT3-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-Laser-AT4-contingency", stat: "Laser-AT4-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser-TankDest2Lgt-contingency", stat: "Laser-TankDest2Lgt-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-Laser-TankDestLgt-contingency", stat: "Laser-TankDestLgt-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-Flame1Mk1", stat: "Flame1Mk1", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Flame2", stat: "Flame2", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-PlasmiteFlamer", stat: "PlasmiteFlamer", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Laser-AT1-contingency", stat: "walltower-Laser-AT1-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AT2-contingency", stat: "walltower-Laser-AT2-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AT3-contingency", stat: "walltower-Laser-AT3-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-AT4-contingency", stat: "walltower-Laser-AT4-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-TankDest2Lgt-contingency", stat: "walltower-Laser-TankDest2Lgt-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser-TankDestLgt-contingency", stat: "walltower-Laser-TankDestLgt-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame1Mk1", stat: "walltower-Flame1Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame2", stat: "walltower-Flame2", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-PlasmiteFlamer", stat: "walltower-PlasmiteFlamer", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Laser-AT1-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AT1-contingency", ] },
			{ res: "R-NRS-Laser-AT2-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AT2-contingency", ] },
			{ res: "R-NRS-Laser-AT3-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AT3-contingency", ] },
			{ res: "R-NRS-Laser-AT4-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-AT4-contingency", ] },
			{ res: "R-NRS-Laser-TankDest2Lgt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-TankDest2Lgt-contingency", ] },
			{ res: "R-NRS-Laser-TankDestLgt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser-TankDestLgt-contingency", ] },
			{ res: "R-NRS-Flame1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Flame1Mk1", ] },
			{ res: "R-NRS-Flame1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "CyborgFlamer01", ] },
			{ res: "R-NRS-Flame2", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Flame2", ] },
			{ res: "R-NRS-Flame2", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Thermite", ] },
			{ res: "R-NRS-PlasmiteFlamer", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "PlasmiteFlamer", ] },
		],
		extras: [
		],
	},
	ASO11 : {
		roles : [ 0.1, 0.2, 0.5, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 140,
		weapons : [
			{ res: "R-NRS-Mortar-Gauss-contingency", stat: "Mortar-Gauss-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Mortar-GaussHvy-contingency", stat: "Mortar-GaussHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar-GaussRamjet-contingency", stat: "Mortar-GaussRamjet-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Mortar-GaussHvyPlas-contingency", stat: "Mortar-GaussHvyPlas-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar-GaussRot-contingency", stat: "Mortar-GaussRot-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar-GaussRotPlas-contingency", stat: "Mortar-GaussRotPlas-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-BB", stat: "Rocket-BB", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-Sunburst", stat: "Rocket-Sunburst", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-BB-2120", stat: "Rocket-BB-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Missile-BB-2120", stat: "Missile-BB-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Rocket-IDF", stat: "Rocket-IDF", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Mortar-Gauss-contingency", stat: "walltower-Mortar-Gauss-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussHvy-contingency", stat: "walltower-Mortar-GaussHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussRamjet-contingency", stat: "walltower-Mortar-GaussRamjet-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussHvyPlas-contingency", stat: "walltower-Mortar-GaussHvyPlas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussRot-contingency", stat: "walltower-Mortar-GaussRot-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussRotPlas-contingency", stat: "walltower-Mortar-GaussRotPlas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-BB", stat: "walltower-Rocket-BB", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-Sunburst", stat: "walltower-Rocket-Sunburst", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-BB-2120", stat: "walltower-Rocket-BB-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-BB-2120", stat: "walltower-Missile-BB-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-IDF", stat: "walltower-Rocket-IDF", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Mortar-Gauss-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-Gauss-contingency", ] },
			{ res: "R-NRS-Mortar-GaussHvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussHvy-contingency", ] },
			{ res: "R-NRS-Mortar-GaussRamjet-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussRamjet-contingency", ] },
			{ res: "R-NRS-Mortar-GaussHvyPlas-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussHvyPlas-contingency", ] },
			{ res: "R-NRS-Mortar-GaussRot-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussRot-contingency", ] },
			{ res: "R-NRS-Mortar-GaussRotPlas-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussRotPlas-contingency", ] },
			{ res: "R-NRS-Rocket-BB", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Rocket-BB", ] },
			{ res: "R-NRS-Rocket-Sunburst", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Rocket-Sunburst", ] },
			{ res: "R-NRS-Rocket-BB-2120", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Rocket-BB-2120", ] },
			{ res: "R-NRS-Missile-BB-2120", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Missile-BB-2120", ] },
			{ res: "R-NRS-Rocket-IDF", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-IDF", ] },
		],
		extras: [
		],
	},
	ASO01 : {
		roles : [ 0.1, 0.2, 0.5, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 142,
		weapons : [
			{ res: "R-NRS-Mortar-Ramjet-contingency", stat: "Mortar-Ramjet-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Mortar-RamjetRot-contingency", stat: "Mortar-RamjetRot-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar-RamjetHvy-contingency", stat: "Mortar-RamjetHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar-GaussRamjetHvy-contingency", stat: "Mortar-GaussRamjetHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Missile-HvyArt", stat: "Missile-HvyArt", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Missile-HvyArt-2120", stat: "Missile-HvyArt-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Mortar-Ramjet-contingency", stat: "walltower-Mortar-Ramjet-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-RamjetRot-contingency", stat: "walltower-Mortar-RamjetRot-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-RamjetHvy-contingency", stat: "walltower-Mortar-RamjetHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar-GaussRamjetHvy-contingency", stat: "walltower-Mortar-GaussRamjetHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-HvyArt", stat: "walltower-Missile-HvyArt", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-HvyArt-2120", stat: "walltower-Missile-HvyArt-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Mortar-Ramjet-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-Ramjet-contingency", ] },
			{ res: "R-NRS-Mortar-RamjetRot-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-RamjetRot-contingency", ] },
			{ res: "R-NRS-Mortar-RamjetHvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-RamjetHvy-contingency", ] },
			{ res: "R-NRS-Mortar-GaussRamjetHvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Mortar-GaussRamjetHvy-contingency", ] },
			{ res: "R-NRS-Missile-HvyArt", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Missile-HvyArt", ] },
			{ res: "R-NRS-Missile-HvyArt-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Missile-HvyArt-2120", ] },
		],
		extras: [
		],
	},
	AWA10 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 26,
		weapons : [
			{ res: "R-NRS-Cannon-Shotgun-contingency", stat: "Cannon-Shotgun-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-HPVAslt-contingency", stat: "Cannon-HPVAslt-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-HPVGattling-contingency", stat: "Cannon-HPVGattling-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon-Sniper-Bunker-contingency", stat: "Cannon-Sniper-Bunker-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Cannon-Shotgun-contingency", stat: "walltower-Cannon-Shotgun-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-HPVAslt-contingency", stat: "walltower-Cannon-HPVAslt-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-HPVGattling-contingency", stat: "walltower-Cannon-HPVGattling-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-Sniper-Bunker-contingency", stat: "walltower-Cannon-Sniper-Bunker-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Cannon-Shotgun-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-Shotgun-contingency", ] },
			{ res: "R-NRS-Cannon-HPVAslt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVAslt-contingency", ] },
			{ res: "R-NRS-Cannon-HPVGattling-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVGattling-contingency", ] },
			{ res: "R-NRS-Cannon-Sniper-Bunker-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-Sniper-Bunker-contingency", ] },
		],
		extras: [
		],
	},
	AWA20 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 30,
		weapons : [
			{ res: "R-NRS-Cannon-HPVLgt-contingency", stat: "Cannon-HPVLgt-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-Cannon-HPVHvy-contingency", stat: "Cannon-HPVHvy-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-HPVTankDestLgt-contingency", stat: "Cannon-HPVTankDestLgt-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-Cannon-HPVTwinAslt-contingency", stat: "Cannon-HPVTwinAslt-contingency", weight: WEIGHT.MEDIUM },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Cannon-HPVLgt-contingency", stat: "walltower-Cannon-HPVLgt-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-HPVHvy-contingency", stat: "walltower-Cannon-HPVHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-HPVTankDestLgt-contingency", stat: "walltower-Cannon-HPVTankDestLgt-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-HPVTwinAslt-contingency", stat: "walltower-Cannon-HPVTwinAslt-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Cannon-HPVLgt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVLgt-contingency", ] },
			{ res: "R-NRS-Cannon-HPVHvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVHvy-contingency", ] },
			{ res: "R-NRS-Cannon-HPVTankDestLgt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVTankDestLgt-contingency", ] },
			{ res: "R-NRS-Cannon-HPVTwinAslt-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-HPVTwinAslt-contingency", ] },
		],
		extras: [
		],
	},
	AWE11 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 34,
		weapons : [
			{ res: "R-NRS-Cannon-Inc-contingency", stat: "Cannon-Inc-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-IncTankDest-contingency", stat: "Cannon-IncTankDest-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-Plas-contingency", stat: "Cannon-Plas-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Cannon-PlasTankDest-contingency", stat: "Cannon-PlasTankDest-contingency", weight: WEIGHT.MEDIUM },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Cannon-Inc-contingency", stat: "walltower-Cannon-Inc-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-IncTankDest-contingency", stat: "walltower-Cannon-IncTankDest-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-Plas-contingency", stat: "walltower-Cannon-Plas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon-PlasTankDest-contingency", stat: "walltower-Cannon-PlasTankDest-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Cannon-Inc-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-Inc-contingency", ] },
			{ res: "R-NRS-Cannon-IncTankDest-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-IncTankDest-contingency", ] },
			{ res: "R-NRS-Cannon-Plas-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-Plas-contingency", ] },
			{ res: "R-NRS-Cannon-PlasTankDest-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon-PlasTankDest-contingency", ] },
		],
		extras: [
		],
	},
	APO01 : {
		roles : [ 0.1, 0.5, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 146,
		weapons : [
			{ res: "R-NRS-MG3Twin-contingency", stat: "MG3Twin-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MG-AntiTankGss-contingency", stat: "MG-AntiTankGss-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-MG-AntiTankGssTwin-contingency", stat: "MG-AntiTankGssTwin-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-MRL", stat: "Rocket-MRL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Missile-MdArt", stat: "Missile-MdArt", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Rocket-IDF-2120", stat: "Rocket-IDF-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Rocket-MRL-Hvy", stat: "Rocket-MRL-Hvy", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG1Mk1-2120", stat: "MG1Mk1-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG7LGTGATTLINGMk1-2120", stat: "MG7LGTGATTLINGMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG7MEDGATTLINGMk1-2120", stat: "MG7MEDGATTLINGMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG7GATTLINGMk1-2120", stat: "MG7GATTLINGMk1-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-MG1Mk1-2120", stat: "MG1-VTOL-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG7LGTGATTLINGMk1-2120", stat: "MG7LGTGATTLING-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG7MEDGATTLINGMk1-2120", stat: "MG7MEDGATTLING-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG7GATTLINGMk1-2120", stat: "MG7GATTLING-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-MG3Twin-contingency", stat: "walltower-MG3Twin-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG-AntiTankGss-contingency", stat: "walltower-MG-AntiTankGss-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG-AntiTankGssTwin-contingency", stat: "walltower-MG-AntiTankGssTwin-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-MRL", stat: "walltower-Rocket-MRL", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-MdArt", stat: "walltower-Missile-MdArt", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-IDF-2120", stat: "walltower-Rocket-IDF-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-MRL-Hvy", stat: "walltower-Rocket-MRL-Hvy", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG1Mk1-2120", stat: "walltower-MG1Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG7LGTGATTLINGMk1-2120", stat: "walltower-MG7LGTGATTLINGMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG7MEDGATTLINGMk1-2120", stat: "walltower-MG7MEDGATTLINGMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG7GATTLINGMk1-2120", stat: "walltower-MG7GATTLINGMk1-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-MG3Twin-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG3Twin-contingency", ] },
			{ res: "R-NRS-MG-AntiTankGss-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG-AntiTankGss-contingency", ] },
			{ res: "R-NRS-MG-AntiTankGssTwin-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG-AntiTankGssTwin-contingency", ] },
			{ res: "R-NRS-Rocket-MRL", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-MRL", ] },
			{ res: "R-NRS-Missile-MdArt", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Missile-MdArt", ] },
			{ res: "R-NRS-Rocket-IDF-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-IDF-2120", ] },
			{ res: "R-NRS-Rocket-MRL-Hvy", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-MRL-Hvy", ] },
			{ res: "R-NRS-MG1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG1Mk1-2120", ] },
			{ res: "R-NRS-MG1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "CyborgChaingun-2120", ] },
			{ res: "R-NRS-MG7LGTGATTLINGMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG7LGTGATTLINGMk1-2120", ] },
			{ res: "R-NRS-MG7LGTGATTLINGMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "CyborgChaingunMed-2120", ] },
			{ res: "R-NRS-MG7MEDGATTLINGMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG7MEDGATTLINGMk1-2120", ] },
			{ res: "R-NRS-MG7GATTLINGMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG7GATTLINGMk1-2120", ] },
		],
		extras: [
		],
	},
	ATO10 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 43,
		weapons : [
			{ res: "R-NRS-Flame1Hvy-contingency", stat: "Flame1Hvy-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Flame1Med-contingency", stat: "Flame1Med-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-Flame2Hvy-contingency", stat: "Flame2Hvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Flame2Med-contingency", stat: "Flame2Med-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Flamer-PlasCan-TankDest-contingency", stat: "Flamer-PlasCan-TankDest-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Flamer-PlasmaCannon-contingency", stat: "Flamer-PlasmaCannon-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Flame1Hvy-contingency", stat: "walltower-Flame1Hvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame1Med-contingency", stat: "walltower-Flame1Med-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame2Hvy-contingency", stat: "walltower-Flame2Hvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame2Med-contingency", stat: "walltower-Flame2Med-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flamer-PlasCan-TankDest-contingency", stat: "walltower-Flamer-PlasCan-TankDest-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flamer-PlasmaCannon-contingency", stat: "walltower-Flamer-PlasmaCannon-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Flame1Hvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame1Hvy-contingency", ] },
			{ res: "R-NRS-Flame1Med-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame1Med-contingency", ] },
			{ res: "R-NRS-Flame2Hvy-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame2Hvy-contingency", ] },
			{ res: "R-NRS-Flame2Med-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame2Med-contingency", ] },
			{ res: "R-NRS-Flamer-PlasCan-TankDest-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flamer-PlasCan-TankDest-contingency", ] },
			{ res: "R-NRS-Flamer-PlasmaCannon-contingency", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flamer-PlasmaCannon-contingency", ] },
		],
		extras: [
		],
	},
	APO11 : {
		roles : [ 0.1, 0.5, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 139,
		weapons : [
			{ res: "R-NRS-MG3Inc-contingency", stat: "MG3Inc-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-MG3IncTwin-contingency", stat: "MG3IncTwin-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MG4Inc-contingency", stat: "MG4Inc-contingency", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-MG4IncTwin-contingency", stat: "MG4IncTwin-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MGPlasSuper-contingency", stat: "MGPlasSuper-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG1Mk1", stat: "MG1Mk1", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-MG2Mk1", stat: "MG2Mk1", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MG3Mk1", stat: "MG3Mk1", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-MG4ROTARYMk1", stat: "MG4ROTARYMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG5TWINROTARY", stat: "MG5TWINROTARY", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG2Mk1-2120", stat: "MG2Mk1-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG3Mk1-2120", stat: "MG3Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG4ROTARYMk1-2120", stat: "MG4ROTARYMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Laser2PULSEMk1-2120", stat: "Laser2PULSEMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Missile-MdArt-2120", stat: "Missile-MdArt-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-MG1Mk1", stat: "MG1-VTOL", weight: WEIGHT.ULTRALIGHT },
			{ res: "R-NRS-MG2Mk1", stat: "MG2-VTOL", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MG3Mk1", stat: "MG3-VTOL", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-MG4ROTARYMk1", stat: "MG4ROTARY-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG2Mk1-2120", stat: "MG2-VTOL-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-MG3Mk1-2120", stat: "MG3-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG4ROTARYMk1-2120", stat: "MG4ROTARY-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Laser2PULSEMk1-2120", stat: "Laser2PULSE-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-MG3Inc-contingency", stat: "walltower-MG3Inc-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG3IncTwin-contingency", stat: "walltower-MG3IncTwin-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG4Inc-contingency", stat: "walltower-MG4Inc-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG4IncTwin-contingency", stat: "walltower-MG4IncTwin-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MGPlasSuper-contingency", stat: "walltower-MGPlasSuper-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG1Mk1", stat: "walltower-MG1Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG2Mk1", stat: "walltower-MG2Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG3Mk1", stat: "walltower-MG3Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG4ROTARYMk1", stat: "walltower-MG4ROTARYMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG5TWINROTARY", stat: "walltower-MG5TWINROTARY", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG2Mk1-2120", stat: "walltower-MG2Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG3Mk1-2120", stat: "walltower-MG3Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG4ROTARYMk1-2120", stat: "walltower-MG4ROTARYMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser2PULSEMk1-2120", stat: "walltower-Laser2PULSEMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-MdArt-2120", stat: "walltower-Missile-MdArt-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-MG3Inc-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG3Inc-contingency", ] },
			{ res: "R-NRS-MG3IncTwin-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG3IncTwin-contingency", ] },
			{ res: "R-NRS-MG4Inc-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG4Inc-contingency", ] },
			{ res: "R-NRS-MG4IncTwin-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG4IncTwin-contingency", ] },
			{ res: "R-NRS-MGPlasSuper-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MGPlasSuper-contingency", ] },
			{ res: "R-NRS-MG1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG1Mk1", ] },
			{ res: "R-NRS-MG1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "CyborgChaingun", ] },
			{ res: "R-NRS-MG2Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG2Mk1", ] },
			{ res: "R-NRS-MG3Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG3Mk1", ] },
			{ res: "R-NRS-MG4ROTARYMk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG4ROTARYMk1", ] },
			{ res: "R-NRS-MG5TWINROTARY", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG5TWINROTARY", ] },
			{ res: "R-NRS-MG5TWINROTARY", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "CyborgRotMG", ] },
			{ res: "R-NRS-MG2Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG2Mk1-2120", ] },
			{ res: "R-NRS-MG3Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG3Mk1-2120", ] },
			{ res: "R-NRS-MG4ROTARYMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG4ROTARYMk1-2120", ] },
			{ res: "R-NRS-MG4ROTARYMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Laser-2120", ] },
			{ res: "R-NRS-Laser2PULSEMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Laser2PULSEMk1-2120", ] },
			{ res: "R-NRS-Laser2PULSEMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-PulseLsr-2120", ] },
			{ res: "R-NRS-Missile-MdArt-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Missile-MdArt-2120", ] },
		],
		extras: [
		],
	},
	ATO01 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 52,
		weapons : [
			{ res: "R-NRS-MG-AntiTank-contingency", stat: "MG-AntiTank-contingency", weight: WEIGHT.LIGHT },
			{ res: "R-NRS-MG-AntiTankTwin-contingency", stat: "MG-AntiTankTwin-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-MG-AntiTank2-contingency", stat: "MG-AntiTank2-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-MG-AntiTank2Twin-contingency", stat: "MG-AntiTank2Twin-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-MG-AntiTank-contingency", stat: "walltower-MG-AntiTank-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG-AntiTankTwin-contingency", stat: "walltower-MG-AntiTankTwin-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG-AntiTank2-contingency", stat: "walltower-MG-AntiTank2-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG-AntiTank2Twin-contingency", stat: "walltower-MG-AntiTank2Twin-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-MG-AntiTank-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG-AntiTank-contingency", ] },
			{ res: "R-NRS-MG-AntiTankTwin-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG-AntiTankTwin-contingency", ] },
			{ res: "R-NRS-MG-AntiTank2-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG-AntiTank2-contingency", ] },
			{ res: "R-NRS-MG-AntiTank2Twin-contingency", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "MG-AntiTank2Twin-contingency", ] },
		],
		extras: [
		],
	},
	ASO00 : {
		roles : [ 0.1, 0.2, 0.5, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 88,
		weapons : [
			{ res: "R-NRS-Howitzer150Mk1-contingency", stat: "Howitzer150Mk1-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGattling-contingency", stat: "HowitzerGattling-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussBB-contingency", stat: "HowitzerGaussBB-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGattlingGauss-contingency", stat: "HowitzerGattlingGauss-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGauss-contingency", stat: "HowitzerGauss-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-HowitzerGaussHvy-contingency", stat: "HowitzerGaussHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussRot-contingency", stat: "HowitzerGaussRot-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Howitzer105Mk1", stat: "Howitzer105Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Howitzer150Mk1", stat: "Howitzer150Mk1", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Howitzer03-Rot", stat: "Howitzer03-Rot", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Howitzer150Mk1-2120", stat: "Howitzer150Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Howitzer150Mk1-contingency", stat: "walltower-Howitzer150Mk1-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGattling-contingency", stat: "walltower-HowitzerGattling-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussBB-contingency", stat: "walltower-HowitzerGaussBB-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGattlingGauss-contingency", stat: "walltower-HowitzerGattlingGauss-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGauss-contingency", stat: "walltower-HowitzerGauss-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussHvy-contingency", stat: "walltower-HowitzerGaussHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussRot-contingency", stat: "walltower-HowitzerGaussRot-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Howitzer105Mk1", stat: "walltower-Howitzer105Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Howitzer150Mk1", stat: "walltower-Howitzer150Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Howitzer03-Rot", stat: "walltower-Howitzer03-Rot", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Howitzer150Mk1-2120", stat: "walltower-Howitzer150Mk1-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Howitzer150Mk1-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Howitzer150Mk1-contingency", ] },
			{ res: "R-NRS-HowitzerGattling-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGattling-contingency", ] },
			{ res: "R-NRS-HowitzerGaussBB-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussBB-contingency", ] },
			{ res: "R-NRS-HowitzerGattlingGauss-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGattlingGauss-contingency", ] },
			{ res: "R-NRS-HowitzerGauss-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGauss-contingency", ] },
			{ res: "R-NRS-HowitzerGaussHvy-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussHvy-contingency", ] },
			{ res: "R-NRS-HowitzerGaussRot-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussRot-contingency", ] },
			{ res: "R-NRS-Howitzer105Mk1", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Howitzer105Mk1", ] },
			{ res: "R-NRS-Howitzer150Mk1", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Howitzer150Mk1", ] },
			{ res: "R-NRS-Howitzer03-Rot", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Howitzer03-Rot", ] },
			{ res: "R-NRS-Howitzer150Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Howitzer150Mk1-2120", ] },
		],
		extras: [
		],
	},
	ATO00 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 65,
		weapons : [
			{ res: "R-NRS-HowitzerRamjet-contingency", stat: "HowitzerRamjet-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-HowitzerRamjetHvy-contingency", stat: "HowitzerRamjetHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerRamjetRot-contingency", stat: "HowitzerRamjetRot-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussRamjet-contingency", stat: "HowitzerGaussRamjet-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-HowitzerGaussRamjetHvy-contingency", stat: "HowitzerGaussRamjetHvy-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussRamjetRot-contingency", stat: "HowitzerGaussRamjetRot-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-HowitzerRamjet-contingency", stat: "walltower-HowitzerRamjet-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerRamjetHvy-contingency", stat: "walltower-HowitzerRamjetHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerRamjetRot-contingency", stat: "walltower-HowitzerRamjetRot-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussRamjet-contingency", stat: "walltower-HowitzerGaussRamjet-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussRamjetHvy-contingency", stat: "walltower-HowitzerGaussRamjetHvy-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussRamjetRot-contingency", stat: "walltower-HowitzerGaussRamjetRot-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-HowitzerRamjet-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerRamjet-contingency", ] },
			{ res: "R-NRS-HowitzerRamjetHvy-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerRamjetHvy-contingency", ] },
			{ res: "R-NRS-HowitzerRamjetRot-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerRamjetRot-contingency", ] },
			{ res: "R-NRS-HowitzerGaussRamjet-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussRamjet-contingency", ] },
			{ res: "R-NRS-HowitzerGaussRamjetHvy-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussRamjetHvy-contingency", ] },
			{ res: "R-NRS-HowitzerGaussRamjetRot-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussRamjetRot-contingency", ] },
		],
		extras: [
		],
	},
	APE00 : {
		roles : [ 0.1, 0.5, 0.2, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 70,
		weapons : [
			{ res: "R-NRS-HowitzerHvyPlas-contingency", stat: "HowitzerHvyPlas-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerRotPlas-contingency", stat: "HowitzerRotPlas-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussInc-contingency", stat: "HowitzerGaussInc-contingency", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-HowitzerGaussHvyPlas-contingency", stat: "HowitzerGaussHvyPlas-contingency", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-HowitzerGaussRotPlas-contingency", stat: "HowitzerGaussRotPlas-contingency", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-HowitzerHvyPlas-contingency", stat: "walltower-HowitzerHvyPlas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerRotPlas-contingency", stat: "walltower-HowitzerRotPlas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussInc-contingency", stat: "walltower-HowitzerGaussInc-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussHvyPlas-contingency", stat: "walltower-HowitzerGaussHvyPlas-contingency", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HowitzerGaussRotPlas-contingency", stat: "walltower-HowitzerGaussRotPlas-contingency", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-HowitzerHvyPlas-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerHvyPlas-contingency", ] },
			{ res: "R-NRS-HowitzerRotPlas-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerRotPlas-contingency", ] },
			{ res: "R-NRS-HowitzerGaussInc-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussInc-contingency", ] },
			{ res: "R-NRS-HowitzerGaussHvyPlas-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussHvyPlas-contingency", ] },
			{ res: "R-NRS-HowitzerGaussRotPlas-contingency", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HowitzerGaussRotPlas-contingency", ] },
		],
		extras: [
		],
	},
	APE11 : {
		roles : [ 0.1, 0.5, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 76,
		weapons : [
			{ res: "R-NRS-Laser3BEAMMk1", stat: "Laser3BEAMMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser2PULSEMk1", stat: "Laser2PULSEMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-AAGunLaser", stat: "AAGunLaser", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser3BEAMMk1-2120", stat: "Laser3BEAMMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Laser4-PlasmaCannon", stat: "Laser4-PlasmaCannon", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-HeavyLaser", stat: "HeavyLaser", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-Laser3BEAMMk1", stat: "Laser3BEAM-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser2PULSEMk1", stat: "Laser2PULSE-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Laser3BEAMMk1-2120", stat: "Laser3BEAM-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-HeavyLaser", stat: "HeavyLaser-VTOL", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-Laser3BEAMMk1", stat: "walltower-Laser3BEAMMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser2PULSEMk1", stat: "walltower-Laser2PULSEMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-AAGunLaser", stat: "walltower-AAGunLaser", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser3BEAMMk1-2120", stat: "walltower-Laser3BEAMMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Laser4-PlasmaCannon", stat: "walltower-Laser4-PlasmaCannon", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-HeavyLaser", stat: "walltower-HeavyLaser", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Laser3BEAMMk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Laser3BEAMMk1", ] },
			{ res: "R-NRS-Laser3BEAMMk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Laser", ] },
			{ res: "R-NRS-Laser2PULSEMk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Laser2PULSEMk1", ] },
			{ res: "R-NRS-AAGunLaser", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "AAGunLaser", ] },
			{ res: "R-NRS-Laser3BEAMMk1-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Laser3BEAMMk1-2120", ] },
			{ res: "R-NRS-Laser4-PlasmaCannon", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Laser4-PlasmaCannon", ] },
			{ res: "R-NRS-HeavyLaser", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "HeavyLaser", ] },
			{ res: "R-NRS-HeavyLaser", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-PulseLsr", ] },
		],
		extras: [
		],
	},
	AWA11 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 117,
		weapons : [
			{ res: "R-NRS-RailGun1Mk1", stat: "RailGun1Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-RailGun2Mk1", stat: "RailGun2Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-RailGun3Mk1", stat: "RailGun3Mk1", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Cannon4AUTOMk1-2120", stat: "Cannon4AUTOMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Cannon1Mk1", stat: "Cannon1Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon2A-TMk1", stat: "Cannon2A-TMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon375mmMk1", stat: "Cannon375mmMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-RailGun1Mk1-2120", stat: "RailGun1Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun2Mk1-2120", stat: "RailGun2Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun3Mk1-2120", stat: "RailGun3Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-RailGun2Mk1", stat: "RailGun2-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon1Mk1", stat: "Cannon1-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon375mmMk1", stat: "MG4ROTARY-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-RailGun1Mk1-2120", stat: "RailGun1-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun2Mk1-2120", stat: "RailGun002-VTOL-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-RailGun3Mk1-2120", stat: "RailGun3-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-RailGun1Mk1", stat: "walltower-RailGun1Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun2Mk1", stat: "walltower-RailGun2Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun3Mk1", stat: "walltower-RailGun3Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon4AUTOMk1-2120", stat: "walltower-Cannon4AUTOMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon1Mk1", stat: "walltower-Cannon1Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon2A-TMk1", stat: "walltower-Cannon2A-TMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon375mmMk1", stat: "walltower-Cannon375mmMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun1Mk1-2120", stat: "walltower-RailGun1Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun2Mk1-2120", stat: "walltower-RailGun2Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun3Mk1-2120", stat: "walltower-RailGun3Mk1-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-RailGun1Mk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "RailGun1Mk1", ] },
			{ res: "R-NRS-RailGun1Mk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Rail1", ] },
			{ res: "R-NRS-RailGun2Mk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "RailGun2Mk1", ] },
			{ res: "R-NRS-RailGun3Mk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "RailGun3Mk1", ] },
			{ res: "R-NRS-RailGun3Mk1", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-RailGunner", ] },
			{ res: "R-NRS-Cannon4AUTOMk1-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cannon4AUTOMk1-2120", ] },
			{ res: "R-NRS-Cannon4AUTOMk1-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "CyborgCannon-2120", ] },
			{ res: "R-NRS-Cannon1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cannon1Mk1", ] },
			{ res: "R-NRS-Cannon2A-TMk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cannon2A-TMk1", ] },
			{ res: "R-NRS-Cannon2A-TMk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-Mcannon", ] },
			{ res: "R-NRS-Cannon375mmMk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cannon375mmMk1", ] },
			{ res: "R-NRS-RailGun1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun1Mk1-2120", ] },
			{ res: "R-NRS-RailGun1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Rail1-2120", ] },
			{ res: "R-NRS-RailGun2Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun2Mk1-2120", ] },
			{ res: "R-NRS-RailGun2Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-RailGunner2-2120", ] },
			{ res: "R-NRS-RailGun3Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun3Mk1-2120", ] },
			{ res: "R-NRS-RailGun3Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-RailGunner-2120", ] },
		],
		extras: [
		],
	},
	AWA21 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 84,
		weapons : [
			{ res: "R-NRS-Cannon5VulcanMk1-2120", stat: "Cannon5VulcanMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Cannon775mmMk1-2120", stat: "Cannon775mmMk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-MG5TWINROTARY-2120", stat: "MG5TWINROTARY-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Cannon6TwinAslt-2120", stat: "Cannon6TwinAslt-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-Cannon5VulcanMk1-2120", stat: "Cannon5Vulcan-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Cannon775mmMk1-2120", stat: "Cannon7-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-Cannon5VulcanMk1-2120", stat: "walltower-Cannon5VulcanMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon775mmMk1-2120", stat: "walltower-Cannon775mmMk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-MG5TWINROTARY-2120", stat: "walltower-MG5TWINROTARY-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon6TwinAslt-2120", stat: "walltower-Cannon6TwinAslt-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Cannon5VulcanMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon5VulcanMk1-2120", ] },
			{ res: "R-NRS-Cannon5VulcanMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-HPV-2120", ] },
			{ res: "R-NRS-Cannon775mmMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon775mmMk1-2120", ] },
			{ res: "R-NRS-Cannon775mmMk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-Lcannon-2120", ] },
			{ res: "R-NRS-MG5TWINROTARY-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "MG5TWINROTARY-2120", ] },
			{ res: "R-NRS-MG5TWINROTARY-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-Mcannon-2120", ] },
			{ res: "R-NRS-Cannon6TwinAslt-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon6TwinAslt-2120", ] },
			{ res: "R-NRS-Cannon6TwinAslt-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-RailHyp-2120", ] },
		],
		extras: [
		],
	},
	ASO10 : {
		roles : [ 0.1, 0.2, 0.5, 0.2 ],
		micro : MICRO.DUMB,
		chatalias : 92,
		weapons : [
			{ res: "R-NRS-Mortar1Mk1", stat: "Mortar1Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar0Mk1-2120", stat: "Mortar0Mk1-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar2Mk1", stat: "Mortar2Mk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Mortar3ROTARYMk1", stat: "Mortar3ROTARYMk1", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Mortar1Mk1", stat: "walltower-Mortar1Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar0Mk1-2120", stat: "walltower-Mortar0Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar2Mk1", stat: "walltower-Mortar2Mk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Mortar3ROTARYMk1", stat: "walltower-Mortar3ROTARYMk1", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Mortar1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Mortar1Mk1", ] },
			{ res: "R-NRS-Mortar1Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Grenade", ] },
			{ res: "R-NRS-Mortar0Mk1-2120", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Mortar0Mk1-2120", ] },
			{ res: "R-NRS-Mortar2Mk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Mortar2Mk1", ] },
			{ res: "R-NRS-Mortar3ROTARYMk1", body: "CyborgLightBody", prop: "CyborgLegs", weapons: [ "Mortar3ROTARYMk1", ] },
		],
		extras: [
		],
	},
	AWA01 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 106,
		weapons : [
			{ res: "R-NRS-Cannon4AUTOMk1", stat: "Cannon4AUTOMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon5VulcanMk1", stat: "Cannon5VulcanMk1", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon6TwinAslt", stat: "Cannon6TwinAslt", weight: WEIGHT.HEAVY },
		],
		vtols : [
			{ res: "R-NRS-Cannon4AUTOMk1", stat: "Cannon4AUTO-VTOL", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Cannon5VulcanMk1", stat: "Cannon5Vulcan-VTOL", weight: WEIGHT.HEAVY },
		],
		defenses : [
			{ res: "R-NRS-Cannon4AUTOMk1", stat: "walltower-Cannon4AUTOMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon5VulcanMk1", stat: "walltower-Cannon5VulcanMk1", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Cannon6TwinAslt", stat: "walltower-Cannon6TwinAslt", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Cannon4AUTOMk1", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon4AUTOMk1", ] },
			{ res: "R-NRS-Cannon4AUTOMk1", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-Acannon", ] },
			{ res: "R-NRS-Cannon5VulcanMk1", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon5VulcanMk1", ] },
			{ res: "R-NRS-Cannon6TwinAslt", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cannon6TwinAslt", ] },
			{ res: "R-NRS-Cannon6TwinAslt", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-HPV", ] },
		],
		extras: [
		],
	},
	ATE21 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 109,
		weapons : [
			{ res: "R-NRS-Flame1Mk1-2120", stat: "Flame1Mk1-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Flame2-2120", stat: "Flame2-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Flame3Mk1-2120", stat: "Flame3Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Flame1Mk1-2120", stat: "walltower-Flame1Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame2-2120", stat: "walltower-Flame2-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Flame3Mk1-2120", stat: "walltower-Flame3Mk1-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Flame1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame1Mk1-2120", ] },
			{ res: "R-NRS-Flame1Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "CyborgFlamer01-2120", ] },
			{ res: "R-NRS-Flame2-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame2-2120", ] },
			{ res: "R-NRS-Flame3Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Flame3Mk1-2120", ] },
			{ res: "R-NRS-Flame3Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Thermite-2120", ] },
		],
		extras: [
		],
	},
	ATO11 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 134,
		weapons : [
			{ res: "R-NRS-Rocket-Pod", stat: "Rocket-Pod", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Rocket-LtA-T", stat: "Rocket-LtA-T", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-Pod-2120", stat: "Rocket-Pod-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-HvyA-T", stat: "Rocket-HvyA-T", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Missile-A-T-2120", stat: "Missile-A-T-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Rocket-LtA-T-2120", stat: "Rocket-LtA-T-2120", weight: WEIGHT.HEAVY },
			{ res: "R-NRS-Rocket-LtA-T2-2120", stat: "Rocket-LtA-T2-2120", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Missile-A-T-2120", stat: "Missile-A-T-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Rocket-Pod", stat: "walltower-Rocket-Pod", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-LtA-T", stat: "walltower-Rocket-LtA-T", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-Pod-2120", stat: "walltower-Rocket-Pod-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-HvyA-T", stat: "walltower-Rocket-HvyA-T", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-A-T-2120", stat: "walltower-Missile-A-T-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-LtA-T-2120", stat: "walltower-Rocket-LtA-T-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-LtA-T2-2120", stat: "walltower-Rocket-LtA-T2-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Missile-A-T-2120", stat: "walltower-Missile-A-T-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Rocket-Pod", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-Pod", ] },
			{ res: "R-NRS-Rocket-LtA-T", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-LtA-T", ] },
			{ res: "R-NRS-Rocket-LtA-T", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Atmiss", ] },
			{ res: "R-NRS-Rocket-Pod-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-Pod-2120", ] },
			{ res: "R-NRS-Rocket-HvyA-T", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-HvyA-T", ] },
			{ res: "R-NRS-Rocket-HvyA-T", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-TK", ] },
			{ res: "R-NRS-Missile-A-T-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Missile-A-T-2120", ] },
			{ res: "R-NRS-Missile-A-T-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-TK-2120", ] },
			{ res: "R-NRS-Rocket-LtA-T-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-LtA-T-2120", ] },
			{ res: "R-NRS-Rocket-LtA-T-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Atmiss-2120", ] },
			{ res: "R-NRS-Rocket-LtA-T2-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Rocket-LtA-T2-2120", ] },
			{ res: "R-NRS-Missile-A-T-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Missile-A-T-2120", ] },
			{ res: "R-NRS-Missile-A-T-2120", body: "CyborgHeavyBody-2120", prop: "CyborgLegs", weapons: [ "Cyb-Wpn-Atmiss2-2120", ] },
		],
		extras: [
		],
	},
	AWO01 : {
		roles : [ 0.4, 0.3, 0.1, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 120,
		weapons : [
			{ res: "R-NRS-RailGun4Mk1-2120", stat: "RailGun4Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun5Mk1-2120", stat: "RailGun5Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun6Mk1-2120", stat: "RailGun6Mk1-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		vtols : [
			{ res: "R-NRS-RailGun4Mk1-2120", stat: "RailGun4-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun5Mk1-2120", stat: "RailGun5-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-RailGun6Mk1-2120", stat: "RailGun6-VTOL-2120", weight: WEIGHT.ULTRAHEAVY },
		],
		defenses : [
			{ res: "R-NRS-RailGun4Mk1-2120", stat: "walltower-RailGun4Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun5Mk1-2120", stat: "walltower-RailGun5Mk1-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-RailGun6Mk1-2120", stat: "walltower-RailGun6Mk1-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-RailGun4Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun4Mk1-2120", ] },
			{ res: "R-NRS-RailGun5Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun5Mk1-2120", ] },
			{ res: "R-NRS-RailGun6Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "RailGun6Mk1-2120", ] },
			{ res: "R-NRS-RailGun6Mk1-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-RailGunner-2120", ] },
		],
		extras: [
		],
	},
	ATO21 : {
		roles : [ 0.5, 0.1, 0.2, 0.2 ],
		micro : MICRO.RANGED,
		chatalias : 127,
		weapons : [
			{ res: "R-NRS-Rocket-HvyA-T-2120", stat: "Rocket-HvyA-T-2120", weight: WEIGHT.ULTRAHEAVY },
			{ res: "R-NRS-Rocket-HvyA-T2-2120", stat: "Rocket-HvyA-T2-2120", weight: WEIGHT.MEDIUM },
			{ res: "R-NRS-Rocket-MRL-2120", stat: "Rocket-MRL-2120", weight: WEIGHT.HEAVY },
		],
		vtols : [
		],
		defenses : [
			{ res: "R-NRS-Rocket-HvyA-T-2120", stat: "walltower-Rocket-HvyA-T-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-HvyA-T2-2120", stat: "walltower-Rocket-HvyA-T2-2120", defrole: DEFROLE.STANDALONE },
			{ res: "R-NRS-Rocket-MRL-2120", stat: "walltower-Rocket-MRL-2120", defrole: DEFROLE.STANDALONE },
		],
		templates: [
			{ res: "R-NRS-Rocket-HvyA-T-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-HvyA-T-2120", ] },
			{ res: "R-NRS-Rocket-HvyA-T-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-A-T-2120", ] },
			{ res: "R-NRS-Rocket-HvyA-T-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-Acannon-2120", ] },
			{ res: "R-NRS-Rocket-HvyA-T2-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-HvyA-T2-2120", ] },
			{ res: "R-NRS-Rocket-HvyA-T2-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Cyb-Hvywpn-A-T2-2120", ] },
			{ res: "R-NRS-Rocket-MRL-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "Rocket-MRL-2120", ] },
			{ res: "R-NRS-Rocket-MRL-2120", body: "CyborgHeavyBody", prop: "CyborgLegs", weapons: [ "CyborgRocket-2120", ] },
		],
		extras: [
		],
	},
	
};
